Feature/compression config
molior-dbs/molior-tools pull request #28
Opened 2020-01-16 16:49 UTC by neolynx

Make the compression method for deployments and inside the initrd installer configurable:
DEPLOYMENT_COMPRESSION = [ none, gzip, xz ]
INSTALLER_COMPRESSION = [ none, gzip, xz ]

2020-01-16 18:01 UTC, hus0 approved these changes

2020-01-16 18:06 UTC, hus0 commented
We should maybe use same variable for all deployments.

2020-01-17 06:46 UTC, hus0 requested changes

2020-01-17 06:46 UTC, hus0 commented on plugins/lxd.plugin
> +         tar $TAR_PXZ -cJf $WORK_DIR/$deployment -C $WORK_DIR metadata.yaml templates rootfs
This doesn't work on stretch as TAR_PXZ is set to `pxz` but `J` option is used for xz.

2020-01-17 07:49 UTC, randombenj approved these changes
Great!

2020-01-17 07:49 UTC, randombenj commented on molior-deploy
> +          log_error "Unsupported deployment compressions: '$DEPLOYMENT_COMPRESSION'"
Maybe add a comment to 'pleas use one of xz, gzip or none'

2020-01-18 15:46 UTC, closed without merging