create-release: support epoch versions
molior-dbs/molior-tools pull request #6
Opened 2019-08-13 19:34 UTC by neolynx

support creating epoch versions, i.e. 1:1.4.2

Signed-off-by: André Roth <neolynx@gmail.com>

2019-08-16 06:27 UTC, szakalboss commented on create-release
> +git tag -a "v$gitversion" -m "$package_name: release $version" >$errlog 2>&1
create new variable and use it

abbrevGitversion="v$gitversion"

2019-08-19 08:59 UTC, randombenj requested changes
Duplicate: https://github.com/molior-dbs/molior-tools/pull/8/commits/6345a0eee10f13ea79864e7b3ca714abb5a70036?

2019-08-21 11:33 UTC, szakalboss approved these changes

2019-08-21 11:41 UTC, neolynx commented
> Duplicate: [6345a0e](https://github.com/molior-dbs/molior-tools/commit/6345a0eee10f13ea79864e7b3ca714abb5a70036)?

no, this is the same and only commit in this PR ;)

2019-08-21 12:29 UTC, merged